# Generated by Django 4.1.7 on 2023-02-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_user_company'),
    ]

    operations = [
    ]
