# Generated by Django 4.1.7 on 2023-02-26 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Antibiotic', 'Antibiotic'), ('Analgesic', 'Analgesic'), ('Anti-inflammatory', 'Anti Inflammatory'), ('Antihistamine', 'Antihistamine'), ('Antihypertensive', 'Antihypertensive'), ('Antimalarial', 'Antimalarial'), ('Antimicrobial', 'Antimicrobial'), ('Vitamins', 'Vitamins'), ('Herbal Medicine', 'Herbal Medicine'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='ingredients',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_photos/'),
        ),
    ]
