# Generated by Django 4.1.7 on 2023-02-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Company',
        ),
    ]
